spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/market
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  type-aliases-package: flab.commercemarket
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

