spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/database/market
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis:
  type-aliases-package: flab.commercemarket
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

imp_key: ENC(TP0S4I3d5gj7hxH5gVSrRCK5PbESBuXWTqPANtm1+h8=)
imp_secret: ENC(F9R6giwITWVe6tXCkiv6rvHX/it3CBJEIibUBLX+3/NPzNT0tqcGe0t