spring:
  datasource:
    master:
      url: ENC(e2cBaAt1JL7IxNalA7pN7kVYg6pg0Y5nTWPjF9UlTkcV0pEfbwrBht76CIqnTnl9)
      username: ENC(0TzQJZvEE7TpaAexvkbLwA==)
      password: ENC(OI5c6BncKMZXJabXAubyfw==)
      driver-class-name: ENC(Bhpswp3jpRS+YqAIXt+8U94M6BqOWpdQP1osszD1FqUBG6SxUMgtDw==)
    slave:
      url: ENC(J/3+BIBO6/ugVfZWB9MDFA7jZc0VtqXUqof87z+ysW8CZitTuSNpUn5SK4vnWZEO)
      username: ENC(03gowqi1UzWEEWdc13bX+A==)
      password: ENC(GOoxTZARqOXfIVa+NWeuSw==)
      driver-class-name: ENC(Bhpswp3jpRS+YqAIXt+8U94M6BqOWpdQP1osszD1FqUBG6SxUMgtDw==)

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mybatis:
    type-aliases-package: flab.commercemarket
    mapper-locations: mybatis/**/*.xml
    configuration:
      map-underscore-to-camel-case: true

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor

iamport:
  host: api.iamport.kr
  imp_key: ENC(TP0S4I3d5gj7hxH5gVSrRCK5PbESBuXWTqPANtm1+h8=)
  imp_secret: ENC(F9R6giwITWVe6tXCkiv6rvHX/it3CBJEIibUBLX+3/NPzNT0tqcGe0tc9QWUoc2bdgFDTYKg5D1YG4mIix2IsWK+Zkdwa+M3IFZHLHp5p9kAUucmExCLIsygMcKDRXG8)